[telegram_notify]
    # Telegram bot token
    token = "YOUR_TOKEN_HERE"

    # Group or user chat id
    chat_id = "YOUR_CHAT_ID_HERE"

    # Interval between notifications in seconds
    notify_interval_sec = 60
